### ISSUE TITLE
central-directory 

### ISSUE THREAD

**Issue by ntamiru** [mojaloop/central-directory#1]
Hello, 

Central-directory Deployment keeps erroring out. Any Idea how to fix the following? 

docker-compose up -d
Pulling postgres (postgres:9.4)...
9.4: Pulling from library/postgres
85b1f47fba49: Pull complete
2d4904bea61e: Pull complete
92fb981a71b7: Pull complete
4dda1edd3e9b: Pull complete
5ea002fc8280: Pull complete
feade6b1bbeb: Pull complete
aeb05e857c87: Pull complete
83691edfca10: Pull complete
303e361540d7: Pull complete
56c4301853ea: Pull complete
ad787351cefd: Pull complete
525663ebdd15: Pull complete
Digest: sha256:4a716c1f80a524f0b77d6ea19c18e692d82425c60c414ab13a560707e910d8dd
Status: Downloaded newer image for postgres:9.4
Building central-directory
Step 1/6 : FROM dwolla/alpine-node-make
latest: Pulling from dwolla/alpine-node-make
Digest: sha256:ab58307ed12c0655fa22a428aa95c635b7d6160b4fa342fabc451de6c8f91594
Status: Downloaded newer image for dwolla/alpine-node-make:latest
 ---> 107ee36aa721
Step 2/6 : WORKDIR /opt/central-directory
 ---> Using cache
 ---> 09ef920bdfb6
Step 3/6 : COPY . /opt/central-directory
 ---> Using cache
 ---> 766241995d22
Step 4/6 : RUN npm link sodium &&   npm link argon2 &&   npm install --production &&   npm uninstall -g npm
 ---> Running in 82c605ca1e43
/opt/central-directory/node_modules/sodium -> /usr/lib/node_modules/sodium
/opt/central-directory/node_modules/argon2 -> /usr/lib/node_modules/argon2
npm ERR! Linux 4.9.49-moby
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.6
npm ERR! code E404

npm ERR! 404 Not found : @mojaloop/central-services-auth
npm ERR! 404 
npm ERR! 404  '@mojaloop/central-services-auth' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of '@mojaloop/central-directory'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/central-directory/npm-debug.log
ERROR: Service 'central-directory' failed to build: The command '/bin/sh -c npm link sodium &&   npm link argon2 &&   npm install --production &&   npm uninstall -g npm' returned a non-zero code: 1

**Comment by bhcrosslake** [comment]
The package.json files are referring to our private JFrog repository for the npm packages. We are working to make that (or another) repository public.

**Comment by bhcrosslake** [comment]
Jeff can you look at this? Are the docker files now updated to pull from the correct registry?

**Comment by mdebarros** [comment]
Closing this issue as its stale & no longer applicable
