### ISSUE TITLE
Error Retrieving Dfsp.

### ISSUE THREAD

**Issue by shajji1** [mojaloop/central-directory#18]
I'm getting this error at **Central-Directory/src/domain/dfsp/index.js:55:56** to resolve this, should i register DFSP via url http://central-directory/commands/register or i need to update configuration in default.json
**My Default.json**
``` 
...
DEFAULT_DFSP: "The first DFSP"
...
```
Please help.

**Comment by HenkKodde** [comment]
Hi @shajji1. You should register using the API provided, using postman or curl.

**Comment by shajji1** [comment]
When i'm using **Manage Phone** option in simulator it response with **User Not Found** and when i Provide destination number in **Send Money** option i got same response.

**Comment by shajji1** [comment]
@HenkKodde  i think the problem with mock-pathfinder it return response with undefined payload. Please help

**Comment by HenkKodde** [comment]
@shajji1  - believe this issue was addressed in one of the other responses back to you regarding the expected behaviour of Mock Pathfinder. I am resolving and closing this issue. If there is anything else we can assist with, please log an issue on the Project Repository.
